trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g newman newman-reporter-htmlextra
      newman run Test_fire.postman_collection.json -r htmlextra --reporter-htmlextra-export $(System.DefaultWorkingDirectory)\newman\index.html
    displayName: 'Run Postman Collection'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)\newman'
      artifact: 'newman-results'
      publishLocation: 'pipeline'
    displayName: 'Publish Newman HTML Report'
