trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- script: |
    npm install -g newman newman-reporter-htmlextra
  displayName: 'Install Newman and Html reporter'
  
- script: mkdir $(Build.ArtifactStagingDirectory)\reports
  displayName: 'Create Reports Directory'

- script: |
    newman run Test_fire.postman_collection.json \
      --reporters cli,htmlextra \
      --reporter-htmlextra-export "$(Build.ArtifactStagingDirectory)\reports\index.html"
  displayName: 'Run API Test'
  continueOnError: true

- task: PublishPipelineArtifact@1
  displayName: 'Publish HTML Report'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/reports'
    ArtifactName: 'Report'